name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkkout Files
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}
          registry: ghcr.io
          repository: NickGalazzo/Carlton-Dashboard-TestBed
          tag_with_ref: false
          build-args: |
            PACKAGE_FEED=https://nuget.pkg.github.com/NickGalazzo/index.json
            PACKAGE_FEED_PAT=${{ secrets.PACKAGE_TOKEN }}
   
