name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkkout Files
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - 
          name: test
          run: pwd
      -
        name: Build Docker Image
        run: docker build -t carlton-dashboard-testbed --build-arg PACKAGE_FEED=https://nuget.pkg.github.com/NickGalazzo/index.json --build-arg PACKAGE_FEED_PAT=${{ secrets.PACKAGE_TOKEN }} .
